DROP DATABASE IF EXISTS SpringBatch_10;
CREATE DATABASE SpringBatch_10;
USE SpringBatch_10;

DROP DATABASE IF EXISTS SpringBatch_10_backup;
CREATE DATABASE SpringBatch_10_backup;
USE SpringBatch_10;

SHOW TABLES;
